In [22]:
import pandas as pd 
df_train= pd.read_csv('Downloads/train (1).csv')
df_test=pd.read_csv('Downloads/test.csv')
y_train=df_train['SalePrice'].values
df_X_train=df_train.drop('SalePrice',axis=1)

In [23]:
#get dummy する際に特徴量に差が出ないようにするためにtrainとtestを一度結合する
df_all=pd.concat([df_X_train, df_test])
df_all.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities      ...       ScreenPorch PoolArea PoolQC Fence  \
0         Lvl    AllPub      ...                 0        0    NaN   NaN   
1         Lvl    AllPub      ...                 0        0    NaN   NaN   
2         Lvl    AllPub      ...                 0        0    NaN   NaN   
3         Lvl    AllPub      ...                 0        0    NaN   NaN   
4         Lvl    AllPub      ...                 0        0    NaN   NaN   

  MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  
0         NaN       0      2    2008        WD         Normal  
1         NaN       0      5    2007        WD         Normal  
2         NaN       0      9    2008        WD         Normal  
3         NaN       0      2    2006        WD        Abnorml  
4         NaN       0     12    2008        WD         Normal  

[5 rows x 80 columns]

In [24]:
#missing data
total= df_all.isnull().sum().sort_values(ascending=False)
percent = (df_all.isnull().sum()/df_all.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data.head(40)

Total   Percent
PoolQC         2909  0.996574
MiscFeature    2814  0.964029
Alley          2721  0.932169
Fence          2348  0.804385
FireplaceQu    1420  0.486468
LotFrontage     486  0.166495
GarageCond      159  0.054471
GarageQual      159  0.054471
GarageYrBlt     159  0.054471
GarageFinish    159  0.054471
GarageType      157  0.053786
BsmtCond         82  0.028092
BsmtExposure     82  0.028092
BsmtQual         81  0.027749
BsmtFinType2     80  0.027407
BsmtFinType1     79  0.027064
MasVnrType       24  0.008222
MasVnrArea       23  0.007879
MSZoning          4  0.001370
BsmtHalfBath      2  0.000685
Utilities         2  0.000685
Functional        2  0.000685
BsmtFullBath      2  0.000685
BsmtFinSF1        1  0.000343
Exterior1st       1  0.000343
Exterior2nd       1  0.000343
BsmtFinSF2        1  0.000343
BsmtUnfSF         1  0.000343
TotalBsmtSF       1  0.000343
SaleType          1  0.000343
Electrical        1  0.000343
KitchenQual       1  0.000343
GarageArea        1  0.000343
GarageCars        1  0.000343
HouseStyle        0  0.000000
LandSlope         0  0.000000
MSSubClass        0  0.000000
LotArea           0  0.000000
Street            0  0.000000
LotShape          0  0.000000

#一般的には15%以上が欠損した場合で特徴量ごと消すが、ここではpreprocessingを簡易化するために一つでも欠損値がある特徴量は削除することにする

In [25]:
#欠損値を含む特徴量の行を消す
df_all=df_all.drop((missing_data[missing_data['Total'] >= 1]).index,1)
df_all.head()

Id  MSSubClass  LotArea Street LotShape LandContour LotConfig LandSlope  \
0   1          60     8450   Pave      Reg         Lvl    Inside       Gtl   
1   2          20     9600   Pave      Reg         Lvl       FR2       Gtl   
2   3          60    11250   Pave      IR1         Lvl    Inside       Gtl   
3   4          70     9550   Pave      IR1         Lvl    Corner       Gtl   
4   5          60    14260   Pave      IR1         Lvl       FR2       Gtl   

  Neighborhood Condition1      ...      WoodDeckSF OpenPorchSF EnclosedPorch  \
0      CollgCr       Norm      ...               0          61             0   
1      Veenker      Feedr      ...             298           0             0   
2      CollgCr       Norm      ...               0          42             0   
3      Crawfor       Norm      ...               0          35           272   
4      NoRidge       Norm      ...             192          84             0   

   3SsnPorch  ScreenPorch  PoolArea  MiscVal MoSold YrSold SaleCondition  
0          0            0         0        0      2   2008        Normal  
1          0            0         0        0      5   2007        Normal  
2          0            0         0        0      9   2008        Normal  
3          0            0         0        0      2   2006       Abnorml  
4          0            0         0        0     12   2008        Normal  

[5 rows x 46 columns]

In [26]:
df_all.dtypes

Id                int64
MSSubClass        int64
LotArea           int64
Street           object
LotShape         object
LandContour      object
LotConfig        object
LandSlope        object
Neighborhood     object
Condition1       object
Condition2       object
BldgType         object
HouseStyle       object
OverallQual       int64
OverallCond       int64
YearBuilt         int64
YearRemodAdd      int64
RoofStyle        object
RoofMatl         object
ExterQual        object
ExterCond        object
Foundation       object
Heating          object
HeatingQC        object
CentralAir       object
1stFlrSF          int64
2ndFlrSF          int64
LowQualFinSF      int64
GrLivArea         int64
FullBath          int64
HalfBath          int64
BedroomAbvGr      int64
KitchenAbvGr      int64
TotRmsAbvGrd      int64
Fireplaces        int64
PavedDrive       object
WoodDeckSF        int64
OpenPorchSF       int64
EnclosedPorch     int64
3SsnPorch         int64
ScreenPorch       int64
PoolArea        

In [27]:
df_all=pd.get_dummies(df_all)
df_all.head()

Id  MSSubClass  LotArea  OverallQual  OverallCond  YearBuilt  YearRemodAdd  \
0   1          60     8450            7            5       2003          2003   
1   2          20     9600            6            8       1976          1976   
2   3          60    11250            7            5       2001          2002   
3   4          70     9550            7            5       1915          1970   
4   5          60    14260            8            5       2000          2000   

   1stFlrSF  2ndFlrSF  LowQualFinSF          ...            CentralAir_Y  \
0       856       854             0          ...                       1   
1      1262         0             0          ...                       1   
2       920       866             0          ...                       1   
3       961       756             0          ...                       1   
4      1145      1053             0          ...                       1   

   PavedDrive_N  PavedDrive_P  PavedDrive_Y  SaleCondition_Abnorml  \
0             0             0             1                      0   
1             0             0             1                      0   
2             0             0             1                      0   
3             0             0             1                      1   
4             0             0             1                      0   

   SaleCondition_AdjLand  SaleCondition_Alloca  SaleCondition_Family  \
0                      0                     0                     0   
1                      0                     0                     0   
2                      0                     0                     0   
3                      0                     0                     0   
4                      0                     0                     0   

   SaleCondition_Normal  SaleCondition_Partial  
0                     1                      0  
1                     1                      0  
2                     1                      0  
3                     0                      0  
4                     1                      0  

[5 rows x 150 columns]

In [33]:
df_X_train=df_all[:1460]
df_X_test=df_all[1460:]
#再びtrainとtestに分ける

In [35]:
X_train=df_X_train.values
X_test=df_X_test.values
#DataFrameからNumpyArrayにする

In [99]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
sc_y=StandardScaler()
X_train_std=sc_x.fit_transform(X_train)
y_train_std=sc_y.fit_transform(y_train)
X_test_std=sc_x.fit_transform(X_test)

/Users/ryuan/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)
/Users/ryuan/anaconda/lib/python3.6/site-packages/sklearn/preprocessing/data.py:586: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/ryuan/anaconda/lib/python3.6/site-packages/sklearn/preprocessing/data.py:649: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


1.KNNでの回帰

In [100]:
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor(n_neighbors=3)
knn.fit(X_train,y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=3, p=2,
          weights='uniform')

In [101]:
print('train set R^2 prediction:{:.2f}'.format(knn.score(X_train,y_train)))
#R^2:coefficient of determination 回帰モデルの予測の正確さを測る指標
#標準化なし

train set R^2 prediction:0.77


In [102]:
knn.fit(X_train_std,y_train_std)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=3, p=2,
          weights='uniform')

In [103]:
print('train_std set R^2 prediction:{:.2f}'.format(knn.score(X_train_std,y_train_std)))
#標準化あり

train_std set R^2 prediction:0.83


In [104]:
sc_y.inverse_transform(knn.predict(X_test_std))

array([ 137300.        ,  196133.33333333,  175200.        , ...,
         99333.33333333,  129000.        ,  179333.33333333])

#標準化ありの方がR^2値が高かったのでそっちの方でtest_dataの予測を行った

問題としてはget dummy のところも標準化してしまってる

2.Random Forestでの回帰

In [105]:
from sklearn.ensemble import RandomForestRegressor
forest = RandomForestRegressor(n_estimators=1000,
                             criterion='mse',
                             random_state=1,
                             )

In [106]:
forest.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=1000, n_jobs=1, oob_score=False, random_state=1,
           verbose=0, warm_start=False)

In [107]:
y_train_pred = forest.predict(X_train)
y_test_pred = forest.predict(X_test)

In [108]:
print('train set R^2 prediction:{:.2f}'.format(forest.score(X_train,y_train)))
#R^2:coefficient of determination 回帰モデルの予測の正確さを測る指標
#標準化なし

train set R^2 prediction:0.98


#Random Forestでは標準化に関係なく行うことができる

#過学習に陥っている可能性が大きい

In [109]:
forest.predict(X_test)

array([ 124406.837,  152424.596,  172820.795, ...,  140860.662,
        128560.825,  234516.602])

In [110]:
forest.feature_importances_

array([  7.57620637e-03,   3.16081537e-03,   2.41403289e-02,
         5.98194202e-01,   5.42084077e-03,   2.34643863e-02,
         1.30906473e-02,   6.20591066e-02,   4.05908046e-02,
         1.94924275e-04,   1.22575296e-01,   6.38014761e-03,
         1.46207416e-03,   2.55462510e-03,   4.27751634e-04,
         7.77701090e-03,   5.71738838e-03,   7.82643282e-03,
         8.02042058e-03,   1.10073601e-03,   8.83339515e-04,
         2.07711935e-03,   7.10838612e-04,   1.14752652e-04,
         5.67412335e-03,   2.77395442e-03,   1.38572746e-05,
         1.70072838e-05,   6.66842158e-04,   6.33142544e-04,
         2.16800638e-04,   2.92424502e-03,   1.36883276e-03,
         3.38960337e-04,   2.74708836e-04,   7.70123786e-04,
         7.64460488e-04,   8.23974393e-04,   1.19631257e-04,
         3.52908575e-05,   6.44976712e-04,   1.09802717e-03,
         3.31351822e-04,   2.09252668e-04,   2.70301609e-05,
         1.55345500e-06,   4.67278260e-05,   1.23435444e-04,
         2.45729176e-04,

#traindata内でも先にtrainとtestに分けて学習すべきだった

3.xgboost での回帰

#xgboostのパッケージの使い方がわからなかったのでsklearnのGradientBoostingRegressorを使って回帰を行う

In [111]:
from sklearn.ensemble import GradientBoostingRegressor
gbrt = GradientBoostingRegressor(random_state=0)
gbrt.fit(X_train, y_train)

print('train set R^2 prediction:{:.2f}'.format(gbrt.score(X_train, y_train)))

train set R^2 prediction:0.95


In [112]:
gbrt.predict(X_test)

array([ 124353.47621955,  158048.34877844,  173919.59672171, ...,
        144754.37120063,  131972.4792729 ,  232516.19953187])

In [113]:
gbrt.feature_importances_

array([  3.47179415e-03,   1.62228973e-03,   9.05622451e-02,
         1.12217699e-01,   4.33049539e-02,   7.46438289e-02,
         3.57573053e-02,   1.02197731e-01,   3.10219343e-02,
         5.64034297e-03,   1.16223873e-01,   2.22416018e-03,
         4.04260051e-03,   7.74041862e-03,   4.71208581e-03,
         1.00974961e-02,   1.32370172e-02,   2.05916090e-02,
         3.15422372e-02,   5.09119524e-03,   2.96987354e-03,
         2.08755704e-02,   1.08280320e-02,   0.00000000e+00,
         5.01740858e-03,   2.70656807e-03,   0.00000000e+00,
         2.23702973e-03,   4.86746785e-04,   0.00000000e+00,
         0.00000000e+00,   9.62378222e-04,   3.96337748e-03,
         0.00000000e+00,   1.63544054e-03,   0.00000000e+00,
         1.82166516e-04,   3.06739740e-03,   0.00000000e+00,
         0.00000000e+00,   1.68975764e-04,   3.93160185e-03,
         4.26236017e-03,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   3.15569048e-03,
         1.09134596e-02,

4.NeuralNetworkでの回帰

In [131]:
from keras.models import Sequential
from keras.layers.core import Dense, Activation, Dropout
from keras.optimizers import Adam
from sklearn.metrics import r2_score

In [115]:
from keras.wrappers.scikit_learn import KerasRegressor

In [116]:
from sklearn.metrics import mean_squared_error

In [124]:
def reg_model():
    model = Sequential()
    model.add(Dense(output_dim=150, input_dim=150, activation='relu'))
    model.add(Dense(output_dim=150, activation='relu'))
    model.add(Dense(output_dim=150, activation='relu'))
    model.add(Dense(output_dim=1))
    #Fully Connect
    # compile model
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model

#入力層のサイズ:150
#中間層の層数:3
#中間層のユニット数:150
#活性化関数:Relu
#loss function:mean_squared_error（平均二乗誤差）
#optimizer:adam(CS231nの第7回参照)

In [125]:
estimator = KerasRegressor(build_fn=reg_model, epochs=100, batch_size=50, verbose=1)
# 標準化なしでトレーニングを行う
estimator.fit(X_train, y_train)

/Users/ryuan/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=150, activation="relu", units=150)`
  app.launch_new_instance()
/Users/ryuan/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=150)`
/Users/ryuan/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=150)`
/Users/ryuan/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1)`


Epoch 1/100
1460/1460 [==============================] - 0s - loss: 32336243277.1507     
Epoch 2/100
1460/1460 [==============================] - 0s - loss: 12490175582.6849     
Epoch 3/100
1460/1460 [==============================] - 0s - loss: 6994766045.8082     
Epoch 4/100
1460/1460 [==============================] - 0s - loss: 5107754867.7260     
Epoch 5/100
1460/1460 [==============================] - 0s - loss: 4383463859.7260     
Epoch 6/100
1460/1460 [==============================] - 0s - loss: 3969738184.7671     
Epoch 7/100
1460/1460 [==============================] - 0s - loss: 3709470189.5890     
Epoch 8/100
1460/1460 [==============================] - 0s - loss: 3441652756.1644     
Epoch 9/100
1460/1460 [==============================] - 0s - loss: 3312202673.9726     
Epoch 10/100
1460/1460 [==============================] - 0s - loss: 3069062109.8082     
Epoch 11/100
1460/1460 [==============================] - 0s - loss: 2894603701.4795     
Epoch 12/100
1460

1460/1460 [==============================] - 0s - loss: 1872695152.6575     
Epoch 92/100
1460/1460 [==============================] - 0s - loss: 1887371262.6849     
Epoch 93/100
1460/1460 [==============================] - 0s - loss: 1889208959.5616     
Epoch 94/100
1460/1460 [==============================] - 0s - loss: 1899704399.5616     
Epoch 95/100
1460/1460 [==============================] - 0s - loss: 1835152987.6164     
Epoch 96/100
1460/1460 [==============================] - 0s - loss: 1922140142.9041     
Epoch 97/100
1460/1460 [==============================] - 0s - loss: 1952777500.4932     
Epoch 98/100
1460/1460 [==============================] - 0s - loss: 1814285651.0685     
Epoch 99/100
1460/1460 [==============================] - 0s - loss: 1842626192.2192     
Epoch 100/100
1460/1460 [==============================] - 0s - loss: 1826233893.6986     


#標準化しないとlossがとんでもない値のまま全く減らない

In [126]:
estimator.predict(X_test)
#標準化なしでの予測

  50/1459 [>.............................] - ETA: 2s

array([ 119330.2421875,  190535.703125 ,  174039.6875   , ...,
        175877.28125  ,  125851.71875  ,  186564.078125 ], dtype=float32)

In [133]:
print('train set R^2 prediction:{:.2f}'.format(r2_score(y_train, estimator.predict(X_train))))

1200/1460 [=======================>......] - ETA: 0strain set R^2 prediction:-5.08


#これは何の値かな（汗

In [128]:
estimator = KerasRegressor(build_fn=reg_model, epochs=100, batch_size=50, verbose=1)
# 標準化ありでトレーニングを行う
estimator.fit(X_train_std, y_train_std)

/Users/ryuan/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=150, activation="relu", units=150)`
  app.launch_new_instance()
/Users/ryuan/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=150)`
/Users/ryuan/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=150)`
/Users/ryuan/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1)`


Epoch 1/100
1460/1460 [==============================] - 1s - loss: 0.4695     
Epoch 2/100
1460/1460 [==============================] - 0s - loss: 0.1948     
Epoch 3/100
1460/1460 [==============================] - 0s - loss: 0.1727     
Epoch 4/100
1460/1460 [==============================] - 0s - loss: 0.1025     
Epoch 5/100
1460/1460 [==============================] - 0s - loss: 0.0725     
Epoch 6/100
1460/1460 [==============================] - 0s - loss: 0.0589     
Epoch 7/100
1460/1460 [==============================] - 0s - loss: 0.0426     
Epoch 8/100
1460/1460 [==============================] - 0s - loss: 0.0332     
Epoch 9/100
1460/1460 [==============================] - 0s - loss: 0.0321     
Epoch 10/100
1460/1460 [==============================] - 0s - loss: 0.0295     
Epoch 11/100
1460/1460 [==============================] - 0s - loss: 0.0263     
Epoch 12/100
1460/1460 [==============================] - 0s - loss: 0.0398     
Epoch 13/100
1460/1460 [=============

#epochは40を超えてからあまり変化がない

In [129]:
sc_y.inverse_transform(estimator.predict(X_test_std))

  50/1459 [>.............................] - ETA: 4s

array([ 129898.3359375,  161648.53125  ,  185971.328125 , ...,
        142826.       ,  152729.25     ,  224878.40625  ], dtype=float32)

In [135]:
print('train_std set R^2 prediction:{:.2f}'.format(r2_score(y_train_std, estimator.predict(X_train_std))))

1250/1460 [========================>.....] - ETA: 0strain_std set R^2 prediction:1.00


#R^2=1.0

反省:
1.先にテストデータの確認を行うべきだった
テストデータの方には目的変数の値がない
2.get dummyした特徴量まで標準化してしまっている

課題:
1.scipyの勉強
get dummyによって列が増え、また成分が0となるものが多い
skewを学ぶ
2.TensorFlowでの実装の勉強
tensorflowの方の実装はあまり理解していない
"詳解ディープラーニング"を勉強
3.欠損値処理とデータ削減
主成分分析とか利用できそう